name: Deploy to Azure Functions

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the deployment on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use appropriate runner based on your requirements

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Azure Functions Core Tools
      run: npm install -g azure-functions-core-tools@3 --unsafe-perm true

    - name: Build and deploy Azure Functions
      run: |
        func azure functionapp publish my-serverless1 --publish-local-settings -i .
      env:
        AzureWebJobsStorage: ${{ secrets.AzureWebJobsStorage }}
        AzureFunctionsAppPath: .
